/*
 * This score code file references one or more analytic stores that are located in the caslib "Models".
 * This score code file references the following analytic-store tables:
 *   _18UBQZCPIXLOAZUT8GDON8CSB_AST
 */
/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2026.02                                                     */
/* Component Version:  V2026.03                                                     */
/* CAS Version:        V.04.00M0P03092026                                           */
/* SAS Version:        V.04.00M0P030926                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       58f34b0a-85f2-4793-bf5f-2e1a22304baf                         */
/* Node GUID:          150a4112-8d94-41e7-8ca8-03bab12699bb                         */
/* Node Id:            18UBQZCPIXLOAZUT8GDON8CSB                                    */
/* Algorithm:          Gradient Boosting                                            */
/* Generated by:       anegas2@emory.edu                                            */
/* Date:               24AUG2026:20:18:27                                           */
/*----------------------------------------------------------------------------------*/
data sasep.out;
   dcl double "CLAGE" having label n'Age of Oldest Credit Line (months)' format COMMA8.1;
   dcl double "CLNO" having label n'Number of Credit Lines';
   dcl double "DEBTINC" having label n'Debt to Income Ratio' format F8.1;
   dcl double "DELINQ" having label n'Number of Delinquent Credit Lines';
   dcl double "DEROG" having label n'Number of Derogatory Reports';
   dcl nchar(7) "JOB" having label n'Job Category';
   dcl double "MORTDUE" having label n'Amount Due on Existing Mortgage' format DOLLAR12.0;
   dcl double "NINQ" having label n'Number of Recent Credit Inquiries';
   dcl nchar(7) "REASON" having label n'Loan Purpose';
   dcl double "VALUE" having label n'Value of Current Property' format DOLLAR12.0;
   dcl double "YOJ" having label n'Years at Present Job';
   dcl package score _18UBQZCPIXLOAZUT8GDON8CSB();
   dcl double EM_EVENTPROBABILITY;
   dcl nchar(12) EM_CLASSIFICATION;
   dcl double "IMP_CLAGE" having label n'Imputed Age of Oldest Credit Line (months)' format COMMA8.1;
   dcl double EM_PROBABILITY;
   dcl double "IMP_CLNO" having label n'Imputed Number of Credit Lines';
   dcl double "IMP_DEBTINC" having label n'Imputed Debt to Income Ratio' format F8.1;
   dcl double "IMP_MORTDUE" having label n'Imputed Amount Due on Existing Mortgage' format DOLLAR12.0;
   dcl double "IMP_VALUE" having label n'Imputed Value of Current Property' format DOLLAR12.0;
   dcl double "IMP_YOJ" having label n'Imputed Years at Present Job';
   dcl double "LOAN" having label n'Amount of Loan Request' format DOLLAR12.0;
   dcl double "MORT_TO_VALUE";
   dcl nchar(7) "IMP_REASON" having label n'Imputed Loan Purpose';
   dcl double "M_CLAGE" having label n'Imputation Indicator for IMP_CLAGE';
   dcl double "M_CLNO" having label n'Imputation Indicator for IMP_CLNO';
   dcl double "M_DEBTINC" having label n'Imputation Indicator for IMP_DEBTINC';
   dcl double "M_DELINQ" having label n'Imputation Indicator for IMP_DELINQ';
   dcl double "M_DEROG" having label n'Imputation Indicator for IMP_DEROG';
   dcl double "M_JOB" having label n'Imputation Indicator for IMP_JOB';
   dcl double "M_MORTDUE" having label n'Imputation Indicator for IMP_MORTDUE';
   dcl double "M_NINQ" having label n'Imputation Indicator for IMP_NINQ';
   dcl double "M_REASON" having label n'Imputation Indicator for IMP_REASON';
   dcl double "M_VALUE" having label n'Imputation Indicator for IMP_VALUE';
   dcl double "M_YOJ" having label n'Imputation Indicator for IMP_YOJ';
   dcl double "IMP_DELINQ" having label n'Imputed Number of Delinquent Credit Lines';
   dcl double "IMP_DEROG" having label n'Imputed Number of Derogatory Reports';
   dcl nchar(7) "IMP_JOB" having label n'Imputed Job Category';
   dcl double "IMP_NINQ" having label n'Imputed Number of Recent Credit Inquiries';
   dcl nchar(19) "CITY" having label n'City';
   dcl double "P_BAD1" having label n'Predicted: BAD=1';
   dcl double "P_BAD0" having label n'Predicted: BAD=0';
   dcl nchar(12) "I_BAD" having label n'Into: BAD';
   dcl nchar(4) "_WARN_" having label n'Warnings';
   varlist allvars [_all_];
 
    
   method init();
      _18UBQZCPIXLOAZUT8GDON8CSB.setvars(allvars);
      _18UBQZCPIXLOAZUT8GDON8CSB.setkey(n'7AFB9B114D52C05CA2933CCEAE5683EA97BBC656');
   end;
    
   method _D4XIZTN2U9V8UVODHAD8RBLKX();
       
      if MISSING("CLAGE") then do ;
      "IMP_CLAGE" = 173.83862388;
      end;
      else "IMP_CLAGE" = "CLAGE";
      if MISSING("CLNO") then do ;
      "IMP_CLNO" = 20.0;
      end;
      else "IMP_CLNO" = "CLNO";
      if MISSING("DEBTINC") then do ;
      "IMP_DEBTINC" = 34.844155434;
      end;
      else "IMP_DEBTINC" = "DEBTINC";
      if MISSING("DELINQ") then do ;
      "IMP_DELINQ" = 0.0;
      end;
      else "IMP_DELINQ" = "DELINQ";
      if MISSING("DEROG") then do ;
      "IMP_DEROG" = 0.0;
      end;
      else "IMP_DEROG" = "DEROG";
      if MISSING("JOB") then do ;
      "IMP_JOB" = 'Other';
      end;
      else "IMP_JOB" = "JOB";
      if MISSING("MORTDUE") then do ;
      "IMP_MORTDUE" = 65136.0;
      end;
      else "IMP_MORTDUE" = "MORTDUE";
      if MISSING("NINQ") then do ;
      "IMP_NINQ" = 0.0;
      end;
      else "IMP_NINQ" = "NINQ";
      if MISSING("REASON") then do ;
      "IMP_REASON" = 'DebtCon';
      end;
      else "IMP_REASON" = "REASON";
      if MISSING("VALUE") then do ;
      "IMP_VALUE" = 89905.0;
      end;
      else "IMP_VALUE" = "VALUE";
      if MISSING("YOJ") then do ;
      "IMP_YOJ" = 7.0;
      end;
      else "IMP_YOJ" = "YOJ";
      if MISSING("CLAGE") then "M_CLAGE" = 1.0;
      else "M_CLAGE" = 0.0;
      if MISSING("CLNO") then "M_CLNO" = 1.0;
      else "M_CLNO" = 0.0;
      if MISSING("DEBTINC") then "M_DEBTINC" = 1.0;
      else "M_DEBTINC" = 0.0;
      if MISSING("DELINQ") then "M_DELINQ" = 1.0;
      else "M_DELINQ" = 0.0;
      if MISSING("DEROG") then "M_DEROG" = 1.0;
      else "M_DEROG" = 0.0;
      if MISSING("JOB") then "M_JOB" = 1.0;
      else "M_JOB" = 0.0;
      if MISSING("MORTDUE") then "M_MORTDUE" = 1.0;
      else "M_MORTDUE" = 0.0;
      if MISSING("NINQ") then "M_NINQ" = 1.0;
      else "M_NINQ" = 0.0;
      if MISSING("REASON") then "M_REASON" = 1.0;
      else "M_REASON" = 0.0;
      if MISSING("VALUE") then "M_VALUE" = 1.0;
      else "M_VALUE" = 0.0;
      if MISSING("YOJ") then "M_YOJ" = 1.0;
      else "M_YOJ" = 0.0;
    
   end;
    
   method _BL1744XGB9Q0QWPZS1P8NQGXC();
       
      if IMP_VALUE > 0.0 then MORT_TO_VALUE = IMP_MORTDUE / IMP_VALUE;
      else MORT_TO_VALUE = .;
    
   end;
    
   method post_18UBQZCPIXLOAZUT8GDON8CSB();
      dcl double _P_;
       
      if "P_BAD0" = . then "P_BAD0" = 0.8005033557;
      if "P_BAD1" = . then "P_BAD1" = 0.1994966443;
      if MISSING("I_BAD") then do ;
      _P_ = 0.0;
      if "P_BAD1" > _P_ then do ;
      _P_ = "P_BAD1";
      "I_BAD" = '           1';
      end;
      if "P_BAD0" > _P_ then do ;
      _P_ = "P_BAD0";
      "I_BAD" = '           0';
      end;
      end;
      EM_EVENTPROBABILITY = "P_BAD1";
      EM_CLASSIFICATION = "I_BAD";
      EM_PROBABILITY = MAX("P_BAD0", "P_BAD1");
    
   end;
    
 
   method run();
      set SASEP.IN;
      _D4XIZTN2U9V8UVODHAD8RBLKX();
      _BL1744XGB9Q0QWPZS1P8NQGXC();
      _18UBQZCPIXLOAZUT8GDON8CSB.scoreRecord();
      post_18UBQZCPIXLOAZUT8GDON8CSB();
   end;
 
   method term();
   end;
 
enddata;
